// packages/doc/src/lib/demo/svelte/With.svelte
<script lang="ts">
  import Likftc from "@likftc/core";
  import { flip } from "svelte/animate";
  import { fade } from "svelte/transition";
  import useFrame from "./useFrame";

  let frame = useFrame();
  const { get, sync } = Likftc($frame);
  $: {
    sync($frame);
  }
</script>

<ul>
  {#each $frame as item (get(item))}
    <li
      animate:flip={{ duration: 1000 }}
      transition:fade|local={{ duration: 1000 }}
    >
      {item}
    </li>
  {/each}
</ul>

// packages/doc/src/lib/demo/vue/With.vue
<script lang="ts" setup>
import Likftc from "@likftc/core";
import { computed, watch } from "vue";
import useFrame from "./useFrame";

let frame = useFrame();

const { get, sync } = Likftc(frame.value);
watch(frame, () => {
  sync(frame.value);
});
</script>

<template>
  <transition-group name="list-complete" tag="ul">
    <li
      v-for="item in frame"
      :key="get(item)"
      class="list-complete-item"
    >
      {{ item }}
    </li>
  </transition-group>
</template>

<style scoped lang="css" src="./style.css"></style>
