// packages/doc/src/lib/demo/react/With.tsx
import useLikftc from "@likftc/react";
import React, { ReactNode } from "react";
import { Flipped, Flipper } from "react-flip-toolkit";
import { v4 } from "uuid";
import { onAppear, onExit } from "./transition";
import useFrame from "./useFrame";

export default function With(): ReactNode {
  const frame = useFrame();
  const { get } = useLikftc(frame, v4);
  return (
    <Flipper flipKey={frame.join(",")}>
      <ul>
        {frame.map((item) => {
          const mapKey = get(item);
          return (
            <Flipped
              key={mapKey}
              flipId={mapKey}
              onAppear={onAppear}
              onExit={onExit}
            >
              <li>{item}</li>
            </Flipped>
          );
        })}
      </ul>
    </Flipper>
  );
}

// packages/doc/src/lib/demo/vue/With.vue
<script lang="ts" setup>
import useLikftc from "@likftc/vue";
import useFrame from "./useFrame";
import { v4 } from "uuid";

let frame = useFrame();
const { get } = useLikftc(frame, v4);
</script>

<template>
  <transition-group name="list-complete" tag="ul">
    <li v-for="item in frame" :key="get(item)" class="list-complete-item">
      {{ item }}
    </li>
  </transition-group>
</template>

<style scoped lang="css" src="./style.css"></style>
